apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: br-region-clusters
  namespace: reverse-words-region
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels:
      region: "BR"
