apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: production-clusters
  namespace: reverse-words-prod
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions:
      - key: region
        operator: In
        values:
          - BR
          - US
    matchLabels: { }
  clusterReplicas: 1
